version: '3.9'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    user: root
    networks:
      - devops-net
    ports:
      - 17251:8081
      - 8085:8085
      - 40000:50000
    volumes:
      - nexus-data:/nexus-data
      - /mnt/c/Users/LENOVO/.m2:/root/.m2

networks:
  devops-net:
    name: devops-net

volumes:
  nexus-data:
