version: "3.9" 
services:
  hadoop:
    image: hadoop:1.0
    hostname: hadoop-master
    container_name: hadoop
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8088:8088"
      - "51070:50070"
      - "2222:22"
    volumes:
      - hdfs-datanote:/opt/hdfs/datanote
    networks:
      - devops-net

  spark:
    image: spark:1.0
    hostname: spark-master
    container_name: spark
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - hadoop
    ports:
      - "18080:18080"
      - "4040:4040"
      - "9080:8080"
      - "2223:22"
      - "7777:7077"
    networks:
      - devops-net

networks:
  devops-net:
    external:
      name: devops-net

volumes:
  hdfs-datanote: