version: "3.9" 
services:
  hadoop:
    image: spark:1.0
    hostname: spark-master
    container_name: spark
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "18080:18080"
      - "4040:4040"
      - "9080:8080"
      - "2223:22"
      - "7077:7077"
    networks:
      - devops-net

networks:
  devops-net:
    external:
      name: devops-net