pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd /var/jenkins_home/workspace/devDocker_main/app/appSpark'
                sh 'mvn -B -DskipTest clean package'
            }
        }
    }
}
