pipeline {
    agent {
        docker {
            image 'maven-nexus:1.0'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd /var/jenkins_home/workspace/devDocker_main/app/appSpark && mvn -B -DskipTest clean package -s settings-nexus.xml'
            }
        }
    }
}
