pipeline {
    agent {
        docker {
            image 'maven:3-jdk-8-alpine'
            args '-v /mnt/c/Users/LENOVO/.m2:/root/.m2'
                }
          }
        environment{
            ArtifactId = readMavenPom().getArtifactId()
            Version = readMavenPom().getVersion()
            Name = readMavenPom().getName()
            GroupId = readMavenPom().getGroupId()
             }
    stages {
        stage('Build')
         {
            steps {
                dir("app")
                    {
                    script {
                        echo $ArtifactId
                        sh 'mvn -B -DskipTest clean package'
                        }
                    }
                  }
         }
         stage ('Publish to Nexus'){
            steps {
                script {
                    sh 'mvn deploy:deploy-file -DgroupId=com.oliver \
                    -DartifactId=spark-setup \
                    -Dversion=1.0-SNAPSHOT \
                    -Dpackaging=jar \
                    -Dfile=target/spark-setup-1.0-SNAPSHOT.jar \
                    -DgeneratePom=true \
                    -DrepositoryId=nexus \
                    -Durl=http://localhost:17251/repository/release/'
                }
            }
         }
    }
}
