pipeline {
    agent {
        docker {
            image 'maven:3-jdk-8-alpine'
            args '-v /mnt/c/Users/LENOVO/.m2:/root/.m2'
        }
        environment {
            workdir '/var/jenkins_home/workspace/devDocker_main/app'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -l /root/.m2'
                sh 'cd $workdir && mvn -B -DskipTest clean package'
            }
        }
    }
}
