pipeline {
    agent {
        docker {
            image 'maven-dan'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -l /root/.m2'
                sh 'cd /var/jenkins_home/workspace/devDocker_main/app && mvn -B -DskipTest clean package -s /root/.m2/settings-dan.xml'
            }
        }
    }
}
